### ISSUE TITLE
测试example里的例子遇到的问题

### ISSUE THREAD

**Issue by Godlikemandyy** [vesoft-inc/nebula-python#100]
![image](https://user-images.githubusercontent.com/36065226/114808003-05c28e80-9dda-11eb-8814-b83347323bb2.png)
修改对应的ip和port后，运行一直出现如下找不到对应spacename：
Traceback (most recent call last):
  File "F:/dongao_dyy/pycharm_projects/hanlp_extract/connect/ngdb_handle.py", line 126, in <module>
    scan_person_vertex(graph_storage_client)
  File "F:/dongao_dyy/pycharm_projects/hanlp_extract/connect/ngdb_handle.py", line 51, in scan_person_vertex
    limit=100)
  File "D:\Anaconda3\envs\hanlp\lib\site-packages\nebula2_python-2.0.0-py3.7.egg\nebula2\sclient\GraphStorageClient.py", line 98, in scan_vertex
    part_leaders = self._meta_cache.get_part_leaders(space_name)
  File "D:\Anaconda3\envs\hanlp\lib\site-packages\nebula2_python-2.0.0-py3.7.egg\nebula2\mclient\__init__.py", line 326, in get_part_leaders
    raise SpaceNotFoundException(space_name)
nebula2.Exception.SpaceNotFoundException: ScanSpace
明明已经存在space:ScanSpace为什么总报这个错误，望指教！！！

**Comment by laura-ding** [comment]
> ![image](https://user-images.githubusercontent.com/36065226/114808003-05c28e80-9dda-11eb-8814-b83347323bb2.png)
> 修改对应的ip和port后，运行一直出现如下找不到对应spacename：
> Traceback (most recent call last):
> File "F:/dongao_dyy/pycharm_projects/hanlp_extract/connect/ngdb_handle.py", line 126, in
> scan_person_vertex(graph_storage_client)
> File "F:/dongao_dyy/pycharm_projects/hanlp_extract/connect/ngdb_handle.py", line 51, in scan_person_vertex
> limit=100)
> File "D:\Anaconda3\envs\hanlp\lib\site-packages\nebula2_python-2.0.0-py3.7.egg\nebula2\sclient\GraphStorageClient.py", line 98, in scan_vertex
> part_leaders = self._meta_cache.get_part_leaders(space_name) File "D:\Anaconda3\envs\hanlp\lib\site-packages\nebula2_python-2.0.0-py3.7.egg\nebula2\mclient__init__.py", line 326, in get_part_leaders
> raise SpaceNotFoundException(space_name)
> nebula2.Exception.SpaceNotFoundException: ScanSpace
> 明明已经存在space:ScanSpace为什么总报这个错误，望指教！！！

9779 是storage的端口，你要用metad的端口9559
