### ISSUE TITLE
AuthFailedException: Insert userIpSessionCount to local cache failed

### ISSUE THREAD

**Issue by doublex** [vesoft-inc/nebula-python#213]
After updating from `3.02` -> `3.1` 
We have a multi-threaded environment - I don't understand this error message:

````
Traceback (most recent call last):
File "/home/mastermind/harmony/nebulaapi.py", line 32, in execute
with connection.session_context(config.nebula['user'], config.nebula['pass']) as session:
File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
return next(self.gen)
File "/home/user/.local/lib/python3.9/site-packages/nebula3/gclient/net/ConnectionPool.py", line 130, in session_context
session = self.get_session(*args, **kwargs)
File "/home/user/.local/lib/python3.9/site-packages/nebula3/gclient/net/ConnectionPool.py", line 109, in get_session
auth_result = connection.authenticate(user_name, password)
File "/home/user/.local/lib/python3.9/site-packages/nebula3/gclient/net/Connection.py", line 112, in authenticate
raise AuthFailedException(resp.error_msg)
nebula3.Exception.AuthFailedException: b'Insert userIpSessionCount to local cache failed.'
````

**Comment by doublex** [comment]
This happens with `nebula-python 3.0` and `nebula-python 3.1` (server always `nebula-graph 3.1`)

**Comment by doublex** [comment]
This is what `nebula-graphd.dbspace.root.log.ERROR` reports:

````
E20220430 16:53:39.828351 22125 GraphService.cpp:97] Create session for userName: nebulauser, ip: ::ffff:1.2.3.4 failed: Insert userIpSessionCount to local cache failed.
E20220430 16:53:44.745187 22127 GraphService.cpp:97] Create session for userName: nebulauser, ip: ::ffff:1.2.3.4 failed: Insert userIpSessionCount to local cache failed.
````

**Comment by doublex** [comment]
I forgot to mention: We use short living connections

**Comment by wey-gu** [comment]
Looks like this is a nebula graph core related, am trying to transfer it there for more exposure.
