### ISSUE TITLE
Unknown error!

### ISSUE THREAD

**Issue by Gavingx** [vesoft-inc/nebula-python#244]
在导入数据的时候报了这个错：
`Traceback (most recent call last):
  File "/home/nlp/graph_data_import/utils/nebula_db.py", line 285, in __init__
    self.client = self.connection_pool.get_session(self.db_info["dbuser"], self.db_info["dbpwd"])
  File "/home/nlp/.local/lib/python3.8/site-packages/nebula2/gclient/net/ConnectionPool.py", line 110, in get_session
    auth_result = connection.authenticate(user_name, password)
  File "/home/nlp/.local/lib/python3.8/site-packages/nebula2/gclient/net/Connection.py", line 105, in authenticate
    raise AuthFailedException(resp.error_msg)
nebula2.Exception.AuthFailedException: b'Create session failed: Unknown error!'

[2022-12-01 17:52:44,592] ERROR    [ConnectionPool.py:215]:The connection using by someone, but now want to close it`
我该怎么解决

**Comment by QingZ11** [comment]
@Gavingx  你的问题解决了么？

**Comment by QingZ11** [comment]
这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
